name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hi! Thanks for helping us find an issue! Developers will be looking into it soon.'
        pr-message: "Hi there! Thanks for contributing to Melody! We'll be checking your awesome code soon!"
